### PR TITLE
Add eldoc and company support using orchardia

### PR DESCRIPTION
**Pull request by pfeodrippe**
Hi @Saikyun, I'd like to add support for autocompletion and eldoc for miracle using code from here (https://github.com/pfeodrippe/orchardia), this repo is basically mixing multiple libraries used by cider-nrepl, but modified to use clojure-clr, so we can have better support for it while making games.

It's written so you can use it without changing the NRepl implementation of Arcadia.

What do you think?

### CODE REVIEW

**Comment by saikyun** [comment]
Hi drippe! Thank you so much! eldoc and company support sounds awesome. I'll take a look soon, but if I forget, don't hesitate to remind me. :)

**Comment by pfeodrippe** [comment]
> Hi drippe! Thank you so much! eldoc and company support sounds awesome. I'll take a look soon, but if I forget, don't hesitate to remind me. :)

Great o/, thanks!

**Comment by saikyun** [comment]
Hi pfeodrippe, I've looked a bit on your PR.

I think you've done some really good work! 👏
Sadly I don't want to add a dependency on cider for miracle, since if you want to use cider + arcadia you can already do so! :)
I understand the need for completion and eldoc though, so I'll take a look on that.

If you still want to use miracle rather than cider, I think it'd be great if you created a plugin containing your changes & additions, and then we can link to that in the readme. :) Even if you replace "core" miracle functions, as long as your code is loaded after miracle, it should work fine.

Sorry if this is not what you wanted to hear. Thank you for taking the time to share this! 🙇

**Comment by pfeodrippe** [comment]
All right, @Saikyun, thanks for your response o/

**Pull request closed without merging**
