### PR TITLE
Add eldoc

### PR DESCRIPTION
**Pull request by pfeodrippe**
At this PR, CIDER dependency is removed by copying what's needed.

Is this what you wanted?

### CODE REVIEW

**Comment by pfeodrippe** [comment]
Ping

**Comment by pfeodrippe** [comment]
Ping

**Comment by saikyun** [comment]
Hey, sorry for not replying. My son has been sick so not much computer time.

Do I understand it correctly; you've copied other people's code without
asking them and attributing it properly? What license is the code under?

I really think it's best if you just create this addition as a plug-in
instead. I don't feel comfortable merging this.


Den fre 7 juni 2019 03:22 skrev Paulo Rafael Feodrippe <
notifications@github.com>:

**Comment by pfeodrippe** [comment]
Oh, ok, @Saikyun. 

I've talked to bbatsov on twitter, the license is
https://github.com/clojure-emacs/cider/blob/master/LICENSE.

I wish the best for you and your son.

Thanks

**Comment by saikyun** [comment]
Aha, I see. It seems that it's okay to copy code pretty liberally then. :) Sorry if I sounded harsh, I just wanted to double check.

But yeah, do create a plugin (or fork if you want to!), I wouldn't mind linking them. :)

**Pull request closed without merging**
